wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.15
    start_time: 1671857647.271657
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 13
      - 23
      - 34
      4: 3.8.15
      5: 0.13.7
      8:
      - 1
      - 4
      - 5
